# Generated by Django 3.2 on 2021-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RA', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('curriculo', models.TextField()),
                ('integralizacao', models.TextField()),
                ('curso', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_prof', models.CharField(max_length=50)),
                ('ic_id', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tem_bolsa', models.BooleanField()),
                ('valor_bolsa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('area', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_divulgacao', models.DateTimeField()),
                ('data_vigente', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_institucional', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('instituto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pagina', models.CharField(max_length=50)),
                ('universidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('proposta', models.TextField()),
                ('data_proposta', models.DateTimeField()),
                ('data_vigente', models.DateTimeField()),
            ],
        ),
    ]
