# Generated by Django 3.2.4 on 2021-06-05 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('divulga_ic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('endDate', models.DateTimeField()),
                ('has_Scholarship', models.BooleanField()),
                ('scholarship_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('subject', models.CharField(max_length=50)),
                ('requirements', models.CharField(max_length=1000)),
                ('workload', models.DecimalField(decimal_places=2, max_digits=4)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulga_ic.advisor')),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Divulgacao',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
