# Generated by Django 3.2.4 on 2021-06-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    def create_data(apps, schema_editor):
        Advisor = apps.get_model('divulga_ic','Advisor')
        Advisor(id=1,email='advisor@advisor.com',name='MyName',department='InstitutoDeComputacao',website='www.mywebsite.com',description='AnAdvisorInterestedInAdvising. In a  b r a n d  b r a v e  w o r l d.')
        IC = apps.get_model('divulga_ic','IC')
        IC(id=2,name='AStudyOnScientificInitiations')

    
    dependencies = [
        ('divulga_ic', '0002_auto_20210605_0451'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]


   
