# Generated by Django 3.2.4 on 2021-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga_ic', '0003_divulga_ic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic',
            name='has_Scholarship',
        ),
        migrations.AddField(
            model_name='ic',
            name='has_scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
